[Dev] Adding realistic output names for stubs
emilyncosta/mtbseq-nf pull request #16
Opened 2021-07-15 00:40 UTC by Mxrcon

Hey, I've fixes the stubs outputs aiming to fix #13 with very simple changes.

This pr only contains new outputs names for the stubs developed before.

I'll e happy on hearing you opinion, feel free to discuss it here! 
I'm at your disposal, Hope we have a merge!
Warmly, Davi

2021-07-15 07:46 UTC, abhi18av requested changes
Hi @Mxrcon , 

Thanks for the PR, we are pretty close already. Just one change overall, mentioned below.

Also, I noticed that the mock data https://github.com/emilyncosta/mtbseq-nf/tree/dev/data/mock_data  `AD04` and `AD05` are incomplete. 

I'd suggest that we keep only 5 samples overall in the mock and remove `AD06` after fixing `AD04/5`

2021-07-15 07:46 UTC, abhi18av commented on modules/mtbseq/tbgroups/tbgroups.nf
> +    touch Groups/${params.mtbseq_project_name}_joint_cf4_cr4_fr75_ph4_samples6_amended_u95_phylo_w12.matrix
Perhaps we should use `samples5` as defined in the `mock_data` folder 

https://github.com/emilyncosta/mtbseq-nf/tree/dev/data/mock_data

2021-07-15 07:46 UTC, abhi18av commented on modules/mtbseq/tbgroups/tbgroups.nf
> +    touch Groups/${params.mtbseq_project_name}_joint_cf4_cr4_fr75_ph4_samples6_amended_u95_phylo_w12.matrix
Therefore `sample5` would be used throughout the stubs in other processes as well.

2021-07-15 15:27 UTC, abhi18av approved these changes
Yup, this looks good to merge now ✅ 

Thanks @Mxrcon!

2021-07-15 15:27 UTC, merged

2021-07-16 00:16 UTC, Mxrcon commented
Thank you Abhinav, i forgot to ask a new review :eyes: